// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://civtlaemwvzkntvloiug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdnRsYWVtd3Z6a250dmxvaXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MjMzNTUsImV4cCI6MjA1NTI5OTM1NX0.aM4lmmt4oMwZrCkojhG13qAGJoncrjT2WnAwJgthh2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);